name: Sync README to index

on:
  push:
    paths:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cp README.md docs/index.md
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.md
          git commit -m "Sync README to index.md" || echo "No changes"
          git push